# Generated by Django 3.2.5 on 2021-07-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_time', models.DateTimeField(auto_now_add=True)),
                ('origin_device', models.CharField(max_length=50)),
                ('message', models.CharField(default='Job is Complete', max_length=200)),
                ('title', models.CharField(default='Untitled Job', max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
