# Generated by Django 3.2.5 on 2021-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='origin_device',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
