# Generated by Django 3.2.5 on 2021-07-11 17:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(default=accounts.models.generate_key, max_length=15),
        ),
    ]
